variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - deploy
  - notify

.artifacts: &artifacts
  name: "animatch-$CI_JOB_NAME-$CI_COMMIT_SHA"
  paths:
    - utils/output/
  expire_in: 90 minutes

build:win64:
  image: dosowisko/libsuperderpy-win64
  stage: build
  retry: 1
  artifacts: *artifacts
  script:
    - cd utils
    - ./package_win64.sh

build:win32:
  image: dosowisko/libsuperderpy-win32
  stage: build
  retry: 1
  artifacts: *artifacts
  script:
    - cd utils
    - ./package_win32.sh

build:linux-steamrt-amd64:
  image: dosowisko/libsuperderpy-linux-amd64
  stage: build
  retry: 1
  artifacts: *artifacts
  script:
    - cd utils
    - NO_STEAM_RUNTIME=1 ./package_linux_amd64.sh

build:linux-steamrt-i686:
  image: dosowisko/libsuperderpy-linux-i686
  stage: build
  retry: 1
  artifacts: *artifacts
  script:
    - cd utils
    - NO_STEAM_RUNTIME=1 ./package_linux_i686.sh

build:linux-flatpak-amd64:
  image: dosowisko/libsuperderpy-flatpak-amd64
  stage: build
  retry: 1
  artifacts: *artifacts
  script:
    - flatpak-builder build-flatpak com.holypangolin.Animatch.json --arch=x86_64 --repo=build-flatpak-repo
    - mkdir -p utils/output
    - flatpak build-bundle build-flatpak-repo utils/output/animatch-linux-amd64.flatpak com.holypangolin.Animatch

build:linux-flatpak-arm64:
  image: dosowisko/libsuperderpy-flatpak-arm64
  stage: build
  retry: 1
  artifacts: *artifacts
  script:
    - update-binfmts --enable qemu-aarch64
    - flatpak-builder build-flatpak com.holypangolin.Animatch.json --arch=aarch64 --repo=build-flatpak-repo
    - mkdir -p utils/output
    - flatpak build-bundle build-flatpak-repo utils/output/animatch-linux-arm64.flatpak com.holypangolin.Animatch

build:macos:
  image: dosowisko/libsuperderpy-macos
  stage: build
  retry: 1
  artifacts: *artifacts
  script:
    - cd utils
    - ./package_osx.sh

deploy:linux-steamrt-i686:
  image: dosowisko/butler
  stage: deploy
  when: on_success
  retry: 2
  environment:
    name: itch-linux-steamrt-i686
    url: https://dos.itch.io/animatch
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build:linux-steamrt-i686
  script:
    - butler push utils/output/animatch-linux-i686.tar.gz dos/animatch:ci-linux-steamrt-i686 --userversion `echo $CI_COMMIT_SHA | cut -c1-7`

deploy:linux-steamrt-amd64:
  image: dosowisko/butler
  stage: deploy
  when: on_success
  retry: 2
  environment:
    name: itch-linux-steamrt-amd64
    url: https://dos.itch.io/animatch
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build:linux-steamrt-amd64
  script:
    - butler push utils/output/animatch-linux-amd64.tar.gz dos/animatch:ci-linux-steamrt-amd64 --userversion `echo $CI_COMMIT_SHA | cut -c1-7`

deploy:linux-flatpak-amd64:
  image: dosowisko/butler
  stage: deploy
  when: on_success
  retry: 2
  environment:    
    name: itch-linux-flatpak-amd64
    url: https://dos.itch.io/animatch
  variables:
    GIT_STRATEGY: none
  dependencies:   
    - build:linux-flatpak-amd64
  script:
    - butler push utils/output/animatch-linux-amd64.flatpak dos/animatch:ci-linux-flatpak-amd64 --userversion `echo $CI_COMMIT_SHA | cut -c1-7`

deploy:linux-flatpak-arm64:
  image: dosowisko/butler
  stage: deploy
  when: on_success
  retry: 2
  environment:
    name: itch-linux-flatpak-arm64
    url: https://dos.itch.io/animatch
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build:linux-flatpak-arm64
  script:
    - butler push utils/output/animatch-linux-arm64.flatpak dos/animatch:ci-linux-flatpak-arm64 --userversion `echo $CI_COMMIT_SHA | cut -c1-7`

deploy:win32:
  image: dosowisko/butler
  stage: deploy
  when: on_success
  retry: 2
  environment:
    name: itch-win32
    url: https://dos.itch.io/animatch
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build:win32
  script:
    - butler push utils/output/animatch-win32.zip dos/animatch:ci-win32 --userversion `echo $CI_COMMIT_SHA | cut -c1-7`

deploy:win64:
  image: dosowisko/butler
  stage: deploy
  when: on_success
  retry: 2
  environment:
    name: itch-win64
    url: https://dos.itch.io/animatch
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build:win64
  script:
    - butler push utils/output/animatch-win64.zip dos/animatch:ci-win64 --userversion `echo $CI_COMMIT_SHA | cut -c1-7`

deploy:macos:
  image: dosowisko/butler
  stage: deploy
  when: on_success
  retry: 2
  environment:
    name: itch-macos
    url: https://dos.itch.io/animatch
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build:macos
  script:
    - butler push utils/output/animatch-osx.zip dos/animatch:ci-macos --userversion `echo $CI_COMMIT_SHA | cut -c1-7`
