.TH animatch 6 2019-11-11 "" "Games Manual"
.SH NAME
.B Animatch
\- a match-three game with cute animals.
.SH SYNOPSIS
.SY animatch
[\fB\-d\fR]
[\fB\-\-debug\fR]
[\fB\-w\fR]
[\fB\-\-windowed\fR]
[\fB\-f\fR]
[\fB\-\-fullscreen\fR]
.YS
.SH DESCRIPTION
.B Animatch
is a match-three game with cute animals. Your task is to swap animal tiles in order to get three
of the same kind into a row.
.SH OPTIONS
.TP
.BR \-d ", " \-\-debug\fR
Enables a debug mode, with on-screen log console and verbose output to stdout.
.TP
.BR \-w ", " \-\-windowed\fR
Launches the game in windowed more, regardless of stored configuration.
.TP
.BR \-f ", " \-\-fullscreen\fR
Launches the game in fullscreen more, regardless of stored configuration.
.SH LICENSE
.B Animatch
is available under the terms of the GNU General Public
License, version 3 or later, as published by the Free Software Foundation <http://gnu.org/licenses/gpl.html>.

This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-3.
.SH REPORTING BUGS
Report bugs to <https://gitlab.com/HolyPangolin/animatch/issues/>.
.SH AUTHOR
Animatch was written by Holy Pangolin <https://holypangolin.com/> studio (Agata Nawrot and Sebastian Krzyszkowiak) for Purism, SPC <https://puri.sm/>.

